version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
          - "5173:80"
    volumes:
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf